import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Legcy blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          legcy <a href="#">Blog</a>
        </h1>
        <p className={styles.description}>
          Best blog page ever 
        </p>
        <Image className={styles.myimg} src="/blog-head.jpg" alt='blogger image' width={550} height={300}/>

        {/* <div className={styles.grid}> */}
        <div className={styles.blogwrap}>
    <h2>Latest blogs</h2>
    <div className={styles.blogitem}>
    <Link href="/blogpost/learn-javascript">
      <h3> how to learn javascript in 2022 </h3></Link>
      <p>Java script is the language used in web technology</p>
      </div>

      <div className={styles.blogitem}>
      <h3>Learn &rarr;</h3>
      <p>how to handle top app</p>
      </div>
  </div>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
